### ISSUE TITLE
Allow lazy evaluation

### ISSUE THREAD

**Issue by cgccuser** [pxeger/whython#3]
For programmers, laziness is a virtue. This can be observed from the popularity of languages such as Haskell. I propose adding lazy values to Whython. Perhaps syntax like `LAZY sorted_list = sorted_list` could be used so that my code runs even if I don't bother to implement a sorting algorithm. I'd do this myself but I'm too lazy to.

**Comment by pxeger** [comment]
unless I'm misunderstanding you, this is way too hard
